<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>swarm_bt_bringup</name>
  <version>0.0.0</version>
  <description>Launch dosyalari ve deney YAML config'leri (hem Faz 1 hem Faz 2 icin).</description>
  <maintainer email="mericesra01@gmail.com">emeric.topaktas</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
